### PR TITLE
Corrected constant colors names

### PR DESCRIPTION
**Pull request by christophetd**
Color.(Lightgreen | Green | Red) should have been in capitals

### CODE REVIEW

**Comment by jpsacha** [comment]
Thanks for the comment.
There is no error there. ScalaFX is encouraging use of Scala-like camel case naming convention rather than Java-like all capitals.

**Comment by christophetd** [comment]
The problem is actually that the example does not compile in Eclipse (and does if we make the case change)

**Comment by Marlo-N** [comment]
Which version of ScalaFX are you using?

**Comment by jpsacha** [comment]
You are likely using an more than a year old version of ScalaFX. Please update to a recent release.

**Pull request closed without merging**
